---
title: "03_02_Algortmo_Expectation_Maximization"
author: "NikolayNikolaev"
date: "2023-03-21"
output: pdf_document
---
### Passo: M
```{r}
y <- matrix(c(10,15, 17, 22, 23, NA),2,3,byrow=TRUE); y

em1 <- function(y23, y){
ystar <- y
ystar[2,3] <- y23
mu.hat <- mean(ystar)
alpha.hat <- apply(ystar, MAR = 1,
mean) - mean(ystar)
beta.hat <- apply(ystar, MAR = 2,
mean) - mean(ystar)
y23 <- mu.hat + alpha.hat[2] + beta.hat[3]
return(c(mu = mu.hat,
alpha = alpha.hat,
beta = beta.hat,
y23 = y23))
}

em1(21,y)

set.seed(1832)
em.step <- function(y, epsilon= 1e-8){
trace <- NULL
convergenza <- FALSE
trace <- t(em1(y23 = mean(y, na.rm = TRUE), y = y))
y23id <- grep("y23", colnames(trace))
h <- 0
while(!convergenza){
h <- h + 1
trace <- rbind(trace,
em1(y23 = trace[h, "y23"],
y = y))
convergenza <- (dist(trace[h:(h+1), -y23id]) < epsilon)
}
return(trace)
}

em.step(y)
```

### Trace Plot:

```{r}
ris<- em.step(y)
matplot(ris[,-7], type = "l")

names1 <- expression(mu,
alpha[1],
alpha[2],
beta[1],
beta[2],
beta[3])
pal1<- c("red", "yellow", "green", "violet", "blue", "orange")
matplot(ris[,-7],
type = "l",
col = pal1,
lwd = 2,
lty = 1,
xlab = "Iterazioni dell'algoritmo EM",
ylab = "Stime dei parametri del modello")
legend(x = 0,
y = 15,
legend = names1,
lwd = 2 ,
col = pal1,
lty = 1,
horiz=TRUE,
cex=0.8)
```



```{r}

```

